### ISSUE TITLE
Missing wslu + version question.

### ISSUE THREAD

**Issue by ygol** [WhitewaterFoundry/Pengwin#474]
I can't find wslu.

Would I have an old version?
```
apt-cache policy pengwin-base
pengwin-base:
  Installed: 0.1-192
  Candidate: 0.1-192
 apt-cache policy pengwin-setup
pengwin-setup:
  Installed: 0.1-851
  Candidate: 0.1-851
```
and content of source.list.d
```
➜  sources.list.d ll
total 4.0K
-rw-r--r-- 1 root root  66 Jun 11 15:28 kelleyk-ubuntu-emacs-eoan.list
-rw-r--r-- 1 root root 480 Jun 11 15:28 whitewaterfoundry.list
-rw-r--r-- 1 root root  47 Jun 11 15:28 yarn.list
➜  sources.list.d cat yarn.list
deb https://dl.yarnpkg.com/debian/ stable main
➜  sources.list.d cat kelleyk-ubuntu-emacs-eoan.list
# deb-src http://ppa.launchpad.net/kelleyk/emacs/ubuntu eoan main
➜  sources.list.d cat whitewaterfoundry.list
deb https://packagecloud.io/whitewaterfoundry/pengwin-base/debian/ buster main
# deb-src https://packagecloud.io/whitewaterfoundry/pengwin-base/debian/ buster main

deb https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian/ buster main
# deb-src https://packagecloud.io/whitewaterfoundry/pengwin-setup/debian/ buster main

deb https://packagecloud.io/whitewaterfoundry/wslu/debian/ buster main
# deb-src https://packagecloud.io/whitewaterfoundry/wslu/debian/ buster main
```

Thank you
